# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #print inputs
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  experiments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: increase version code
        run: |
          echo "$(pwd)"
          FILE=sudoq-app/sudoqapp/src/main/AndroidManifest.xml
          LINE_NUMBER=grep -n "android:versionCode=" $FILE | cut -f1 -d:
          VERSION=$(sed -n ${LINE_NUMBER}p $FILE | grep -oE '[0-9]+')
          sed -i "${LINE_NUMBER}s/${VERSION}/$((VERSION+1))/" $FILE
          
      - name: increase version number
        run : |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}" 
