# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      changeSeverity:
        description: 'how severe are the changes? chose from b,n,p'     
        required: true
        default: 'p'
      tags:
        description: 'Test scenario tags'  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #print inputs
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.changeSeverity }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  experiments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: increase version code
        env:
          FILE: sudoq-app/sudoqapp/src/main/AndroidManifest.xml
        run: |
          echo "$(pwd)"
          echo "get line number"
          LINE_NUMBER=$(grep -n "android:versionCode=" $FILE | cut -f1 -d:)
          echo "get version"
          VERSION=$(sed -n ${LINE_NUMBER}p $FILE | grep -oE '[0-9]+')
          echo "replace version"
          sed -i "${LINE_NUMBER}s/${VERSION}/$((VERSION+1))/" $FILE
          
      - name: increase version number
        run : |
          FILE=sudoq-app/sudoqapp/src/main/AndroidManifest.xml
          echo "$(ls)"
          python .github/workflows/incrementVersionName.py ${{ github.event.inputs.changeSeverity }} $FILE
          echo "Log level: ${{ github.event.inputs.changeSeverity }}"
          echo "Tags: ${{ github.event.inputs.tags }}" 
          
      - name: commit files
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: increase version
          title: '[Experiment] increase version'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: report, automated pr
                    
